# Generated by Django 5.0 on 2024-01-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="color",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="cat",
            name="gender",
            field=models.BooleanField(default=0),
        ),
    ]
