# Generated by Django 4.2.18 on 2025-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_filemodel_delete_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
